services:
  streamlit-dashboard-simple:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: sql-server-dashboard-simple
    ports:
      - "8503:8501"  # Different port for simple environment
    environment:
      # TEST MODE - No SQL Server or Entra ID required
      - TEST_MODE=true
      
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    
    volumes:
      # Mount test configuration and dummy data
      - ./test_data:/app/test_data:ro
      
      # Mount cache directory for persistent target hours (test data)
      - ./cache:/app/cache
      
      # Mount logs directory
      - ./logs:/app/logs
    
    networks:
      - simple-dashboard-network
    
    restart: unless-stopped
    
    # Resource limits (reduced for test environment)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Labels for easy identification
    labels:
      - "environment=test"
      - "purpose=demo"
      - "project=sql-server-dashboard"
      - "type=simplified"

networks:
  simple-dashboard-network:
    driver: bridge
    labels:
      - "environment=test"
      - "type=simplified"
